# Generated by Django 4.1.3 on 2022-11-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="config",
            name="date_expired",
        ),
        migrations.RemoveField(
            model_name="config",
            name="date_published",
        ),
        migrations.RemoveField(
            model_name="config",
            name="state",
        ),
        migrations.AlterField(
            model_name="config",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date of creation"),
        ),
    ]
