# Generated by Django 4.1.3 on 2022-11-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="date_created",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="date_deleted",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="date_expired",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="date_published",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="date_updated",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="question",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="state",
        ),
        migrations.AddField(
            model_name="contact",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=25, null=True, verbose_name="First Name"
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="last_name",
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name="Last Name"),
        ),
        migrations.AddField(
            model_name="contact",
            name="phone",
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name="Phone"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="message",
            field=models.TextField(verbose_name="Message"),
        ),
    ]
