# Generated by Django 4.1.3 on 2022-11-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0002_auto_20180920_1245"),
    ]

    operations = [
        migrations.AlterField(
            model_name="translation",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="translation",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("fr", "Français"), ("nl", "Nederlands")],
                help_text="the language of the translation",
                max_length=32,
                verbose_name="language",
            ),
        ),
    ]
