# Generated by Django 4.1.3 on 2022-11-18 14:16

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cookie",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Unique identification",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date of creation"),
                ),
                (
                    "date_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Date of last update"),
                ),
                (
                    "date_deleted",
                    models.DateTimeField(blank=True, null=True, verbose_name="Delete date"),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="Title"),
                ),
                (
                    "message",
                    models.TextField(blank=True, null=True, verbose_name="Message"),
                ),
                (
                    "essential_functional_cookies_description",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Essential and functional cookie description",
                    ),
                ),
                (
                    "analytical_cookies_description",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Analytical cookie description",
                    ),
                ),
                (
                    "external_content_cookies_description",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="External content cookie description",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cookie",
                "verbose_name_plural": "Cookie's",
            },
        ),
    ]
